### ISSUE TITLE
[기능]webOS의 mqtt client에서 subscribe한 값들 firebase에 저장

### ISSUE THREAD

**Issue by sanglee2** [perman0519/2024ESWContest_webOS_3016#1]
**구현할 기능 설명**
web application(mqtt client)가 구독한 온습도 센서, 토양습도 센서 값을 firebase에 저장한다.

**기능 구현을 위해 해야할 것**
1. Firebase 설정 (= Firebase SDK를 프로젝트에 통합하기)
2. MQTT 수신메시지를 Firestore에 저장
3. Firebase 콘솔로 Firestore 데이터 확인

**Comment by ph-han** [comment]
very good!
today the farm sensor will be combined into one esp8266
